# Generated by Django 5.0.1 on 2024-02-08 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorant', '0006_remove_restaurant_owner_alter_restaurant_logo_url'),
        ('users', '0002_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='restorant.restaurant'),
        ),
    ]
