# Generated by Django 5.0.2 on 2024-03-03 04:28

import restorant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo_url',
            field=models.ImageField(blank=True, upload_to=restorant.models.restaurant_image_directory_path),
        ),
    ]
