# Generated by Django 5.0.1 on 2024-01-28 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restorant', '0003_restaurant_qr_code_restaurant_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='url',
        ),
    ]
