# Generated by Django 5.0.1 on 2024-02-08 06:44

import restorant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorant', '0005_restaurant_qr_code_restaurant_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='owner',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo_url',
            field=models.ImageField(blank=True, upload_to=restorant.models.restaurant_image_directory_path),
        ),
    ]
