# Generated by Django 5.0.1 on 2024-02-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restorant', '0006_remove_restaurant_owner_alter_restaurant_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='qr_code',
        ),
    ]
